In [15]:
import numpy as np 
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM,Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [16]:
data = [
"bugün hava top oynamak için çok güzel",
"yarın okula gitmicem çünkü hastayım",
"annemle markete gittik ama hiç bişey almadık",
"dün akşam çok geç yattım sabah kalkamadım",
"bana bunu niye söylemedinki anlamadım",
"arkadaşlarla sinemaya gitcez ama saat belli değil",
"telefonumu evde unutmuşum bütün gün sıkıldım",
"sen gelirmisin yoksa benmi geleyim",
"bu kadar yorgunken ders çalışamamki",
"bunu yapmayı denicem ama zor gibi",
"beni aramışsın ama duymadım kusura bakma",
"yarın sınav var ama daha hiç çalışmadım",
"benimle gelmek istermisin diye sormadın",
"yemek çok güzeldi ellerine sağlık ama doymadım",
"otobüsü kaçırdım okula geç kaldım",
"şimdi napıcaz bilmiyorum çok karışık",
"bana verdiğin kitap çok güzeldi bitirdim",
"dışarda hava çok soğuk mont almadan çıkma",
"bu soruyu çözemedim çok zor geldi",
"sen neden böyle yaptın anlam veremedim",
"birazdan gelicem bekle beni",
"yolda trafik vardı o yüzden geç kaldım",
"ben sana demedimmi böyle olacağını",
"çok uykum var ama uyuyamıyorum",
"dersler çok zorlaştı artık yetişemiyorum",
"bu filmi daha önce izlemişmiydik hatırlamıyorum",
"seninle konuşcak çok şeyim var",
"bu kadar hızlı koşma düşebilirsin",
"bunu bana daha önce söylemişmiydin",
"evde kimse yok canım çok sıkıldı",
"bunu yaparsak daha iyi olur bence",
"neden böyle düşündüğünü anlamıyorum",
"ben gelene kadar burda bekle",
"şimdi dışarı çıkmak istemiyorum çok yorgunum",
"yemek hazır olunca bana haber ver",
"benim için farketmez sen nasıl istersen",
"bu işi bugün bitirmemiz lazım yoksa sorun olur",
"ben sana güveniyorum ama dikkatli ol",
"yarın erken kalkmam lazım o yüzden uyuyorum",
"sen gelmeden önce herşeyi hazırladım",
"çok güzel bir gündü keşke bitmeseydi",
"ben bunu tek başıma yapamam yardım et",
"neden böyle yaptığını bana açıklarmısın",
"bugün hiç bişey yapmak istemiyorum",
"senin dediğin gibi yapmayı denedim olmadı",
"bu kadar bekleyeceğimi bilmiyordum",
"herkes gelmiş bir tek sen yoksun",
"bunu yanlış yaptım galiba tekrar denicem",
"ben sana sonra geri dönüş yaparım",
"şimdi konuşmak istemiyorum daha sonra ararım"
"bugün çok işim vardı ama hiç birini yapamadım",
"sen neden bana hiç yazmıyosun merak ediyorum",
"yarın erken kalkcam ama uykum hiç yok",
"akşam yemeğini yemeden çıktım çok acıktım",
"bu kadar zor olacağını düşünmemiştim açıkçası",
"benimle konuşmak istemiyosan söyle lütfen",
"ders çalışıcam dedim ama yine yapmadım",
"annem beni çağırdı ama duymamazlıktan geldim",
"sen gelicekmisin yoksa iptalmi oldu",
"bu konuyu anlamadım tekrar anlatabilirmisin",
"çok yoruldum artık dinlenmek istiyorum",
"yarın görüşürüz belki bi kahve içeriz",
"ben sana güvenmiştim ama hayal kırıklığı oldu",
"telefonun şarjı bittiği için ulaşamadım",
"şimdi ne yapacağımızı bilmiyorum kararsızım",
"bu kadar beklemek zorunda değildim aslında",
"seninle gelmek istedim ama fırsat olmadı",
"bugün hava çok güzeldi dışarı çıkmadım",
"yemek yapmayı denedim ama pek iyi olmadı",
"bunu sana anlatmak istiyodum ama unuttum",
"herşey çok hızlı gelişti ne olduğunu anlamadım",
"ben gelene kadar başlamayın lütfen",
"senin dediğin şeyi yapmaya çalıştım olmadı",
"çok geç kaldım ama elimde değildi",
"yarın plan yapalım mı müsaitsen",
"benim için önemliydi ama sen farketmedin",
"bu kadar insanın içinde seni göremedim",
"neden böyle davrandığını anlamıyorum hala",
"ben sana mesaj attım ama görmedin galiba",
"aklım çok karışık ne yapacağımı bilmiyorum",
"bugün hiç iyi hissetmiyorum biraz kötüyüm",
"sen gelmeden önce herşeyi bitirdik",
"ben sana bunu daha önce söylemiştim sanki",
"çok fazla şey oldu kafam doldu",
"yarın okula gitmek istemiyorum açıkçası",
"benimle konuşmayı kesmişsin neden",
"bu işi hallederiz merak etme",
"seninle vakit geçirmek çok güzeldi",
"ben bunu yanlış anlamış olabilirim",
"çok açım ama yemek yapmaya üşeniyorum",
"neden bana böyle söyledin üzüldüm",
"bu kadarını beklemiyordum doğrusu",
"senin yüzünden geç kaldım gibi oldu",
"ben gelmeden sakın başlama tamam mı",
"yarın sınav var ama hiç hazır değilim",
"bu sorunun cevabını bilmiyorum",
"benim için önemli olan senin gelmen",
"çok düşündüm ama karar veremedim",
"bana biraz zaman ver lütfen",
"şimdi çıkmam lazım sonra konuşuruz"
]

In [17]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data)
total_words = len(tokenizer.word_index) + 1
print(f"total_words: {total_words}")

total_words: 321


In [18]:
input_sequences = []
for text in data:
    token_list = tokenizer.texts_to_sequences([text])[0]
    for i in range(1, len(token_list)):
        n_gram_sequnce =token_list[: i+1]
        input_sequences.append(n_gram_sequnce)

print(f"input_sequences: \n{input_sequences}")

input_sequences: 
[[15, 29], [15, 29, 87], [15, 29, 87, 88], [15, 29, 87, 88, 16], [15, 29, 87, 88, 16, 1], [15, 29, 87, 88, 16, 1, 46], [7, 30], [7, 30, 89], [7, 30, 89, 90], [7, 30, 89, 90, 91], [92, 93], [92, 93, 94], [92, 93, 94, 2], [92, 93, 94, 2, 8], [92, 93, 94, 2, 8, 47], [92, 93, 94, 2, 8, 47, 95], [96, 48], [96, 48, 1], [96, 48, 1, 17], [96, 48, 1, 17, 97], [96, 48, 1, 17, 97, 98], [96, 48, 1, 17, 97, 98, 99], [9, 5], [9, 5, 100], [9, 5, 100, 101], [9, 5, 100, 101, 31], [102, 103], [102, 103, 104], [102, 103, 104, 2], [102, 103, 104, 2, 105], [102, 103, 104, 2, 105, 106], [102, 103, 104, 2, 105, 106, 107], [108, 49], [108, 49, 109], [108, 49, 109, 110], [108, 49, 109, 110, 111], [108, 49, 109, 110, 111, 112], [6, 113], [6, 113, 32], [6, 113, 32, 114], [6, 113, 32, 114, 115], [3, 10], [3, 10, 116], [3, 10, 116, 50], [3, 10, 116, 50, 117], [5, 33], [5, 33, 51], [5, 33, 51, 2], [5, 33, 51, 2, 34], [5, 33, 51, 2, 34, 35], [36, 118], [36, 118, 2], [36, 118, 2, 119], [36, 118, 2, 

In [19]:
max_sequence_lenght = max(len(x) for x in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen = max_sequence_lenght, padding = "pre")

print(f"after padding input_sequences: \n{input_sequences}")

after padding input_sequences: 
[[  0   0   0 ...   0  15  29]
 [  0   0   0 ...  15  29  87]
 [  0   0   0 ...  29  87  88]
 ...
 [  0   0   0 ...  18 319  41]
 [  0   0   0 ... 319  41  43]
 [  0   0   0 ...  41  43 320]]


In [20]:
X = input_sequences[:, :-1]
y = input_sequences[: -1]

y = tf.keras.utils.to_categorical(y, num_classes= total_words)
print(f"hedef değişken: {y}")

hedef değişken: [[[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 1. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 

In [21]:
model = Sequential()
model.add(Embedding(total_words, 50, input_length= X.shape[1]))
model.add(LSTM(100))
model.add(Dense(total_words, activation= "softmax"))
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

print(model.summary())

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [29]:
print(len(X))
print(len(y))

475
475


In [30]:
print(X.shape)
print(y.shape)

(475, 12)
(475, 321)


In [31]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [32]:
Dense(321, activation='softmax')

<Dense name=dense_3, built=False>

In [33]:
model.add(Embedding(input_dim=321, output_dim=100, input_length=12))

c:\Users\Zehra\Desktop\lstm-ile-metin-olusturma\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [34]:
model = Sequential()

model.add(Embedding(input_dim=321, output_dim=100, input_length=12))
model.add(LSTM(150))
model.add(Dense(321, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0358 - loss: 5.7651  
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0463 - loss: 5.6206
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0442 - loss: 5.4793   
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0484 - loss: 5.4284
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0463 - loss: 5.4028
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0505 - loss: 5.3588   
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0505 - loss: 5.2965
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0632 - loss: 5.2243
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0632 - loss: 5.1450
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0863 - loss: 5.0432
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0947 - loss: 4.9289
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - a

In [38]:
def generate_text(seed_text, next_words):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list],maxlen = max_sequence_lenght - 1, padding = "pre")
        predicted_probs = model.predict(token_list, verbose = 0)
        predicted_index = np.argmax(predicted_probs, axis = -1)[0]
        predicted_words = tokenizer.index_word[predicted_index]
        seed_text = seed_text +" " + predicted_words
    return seed_text

print(generate_text("Bugün ",5))



Bugün  hiç bişey yapmak istemiyorum istemiyorum
